### ISSUE TITLE
Feature Request: Use LDAP instead of WinRM

### ISSUE THREAD

**Issue by MartineDesroubins** [PSSecTools/Krbtgt#8]
We looking for a switch to use LDAP instead of WinRM for the force sync. Is that possible?

**Comment by FriedrichWeinmann** [comment]
Very possible, added to the todo list :)

**Comment by MartineDesroubins** [comment]
Hey do you had time to look at this :-)

**Comment by FriedrichWeinmann** [comment]
Implemented in 1.1.7
